name: KODUS
email: kbellioum@itknowledgema.com
description: > #KODUS Conseil en menuiserie aluminium
baseurl: ""
url: ""
#https://www.itknowledge.ma/koduslast
# Cloudinary assets
logo: https://res.cloudinary.com/kbellioum/image/upload/v1497787353/kodus_xbdlh7.png

#https://res.cloudinary.com/kbellioum/image/upload/v1496072295/kodus_w4mh2k.png

# Build settings
markdown: kramdown
highlighter: rouge

paginate: 5
paginate_path: "/blogs/page:num/"

sass:
  sass_dir: assets/styles
  style: compressed

collections:
  blogs:
    output: true
    permalink: /:categories/:year/:month/:day/:title.html

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

exclude: ['Rakefile', 'config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'bin']

port:    4001
