name: KODUS
email: kbellioum@itknowledgema.com
description: "Kodus , Conseil en travaux de menuiserie aluminium.
Nous opérons dans les projets d’aménagement , Extension, Rénovation.
Nous intervenons dans le traitement de façade , Isolation acoustique et thermique , Cloisonnement des espaces.
Nous vous proposons la solution adéquate pour vos projets de Villas ,Hôtels , Restaurants, Cafés et Appartements."
  # > #KODUS Conseil en menuiserie aluminium
baseurl: ""
url: "https://www.kodusdb.com"
sss: "https://www.kodusdb.com"
#https://www.itknowledge.ma/koduslast
# Cloudinary assets
logo: https://res.cloudinary.com/kbellioum/image/upload/v1497787353/kodus_xbdlh7.png

#https://res.cloudinary.com/kbellioum/image/upload/v1496072295/kodus_w4mh2k.png

# Build settings
markdown: kramdown
highlighter: rouge

paginate: 5
paginate_path: "/blog/page:num/"
paginate_path: "/gallery/page:num/"

sass:
  sass_dir: assets/styles
  style: compressed

collections:
  blog:
    output: true
    permalink: /:categories/:year/:month/:day/:title.html
  gallery:
    output: true
    permalink: /:categories/:year/:month/:day/:title.html

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
plugins_dir:
  - jekyll-sitemap

exclude: ['Rakefile', 'config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'bin']

port:    4001
